### PR TITLE
0328

### PR DESCRIPTION
**Pull request by jefflien8**
http://3.229.198.70:3000/
http://3.229.198.70:3000/attraction/2

連崇甫繳交PART4作業! 請老師過目~

### CODE REVIEW

**Comment by cwpeng** [comment]
`<!DOCTYPE CSS>` is wrong declaration in your every pages.

**Comment by jefflien8** [comment]
已修正 感謝老師

**Comment by cwpeng** [comment]
We should show error message for user if sign in with wrong email or password.

**Comment by jefflien8** [comment]
已更新 請老師複查

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
