### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jefflien8**
http://3.229.198.70:3000/attraction/11
http://3.229.198.70:3000/attraction/1
http://3.229.198.70:3000/
老師好 連崇甫繳交Week3的作業

### CODE REVIEW

**Comment by jefflien8** [comment]
忘記Add reviewer了QQ

**Comment by cwpeng** [comment]
1. Layout exceeds screen width in small to middle size devices. (<1200px)
2. Navigator content should align center vertically.

未命名-2

**Comment by jefflien8** [comment]
已修正!

**Comment by cwpeng** [comment]
1. No fix.
2. OK.

**Comment by jefflien8** [comment]
已修正了!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
