### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jefflien8**
http://3.229.198.70:3000/

老師好! 連崇甫繳交第二周作業

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Content of navigator, key visual section, and attraction list should align with each other both on left or right side in the large devices. (screen width >1200px)
2. Border of search box and icon should be in the same style as design.
3. Content of key visual section should align left with 台北一日遊 in the small devices (screen width < 500px)
4. Too slow to load next page of data when we scroll down to the bottom of page.


3 229 198 70_3000_(Samsung-Galaxy-S8+)

**Comment by jefflien8** [comment]
已修正! 再麻煩老師檢查

**Comment by cwpeng** [comment]
1. OK.
2. OK.
3. No changes.
4. OK.

Fix issue 3.

**Comment by jefflien8** [comment]
已修正! 拍謝又要麻煩老師了><

**Comment by cwpeng** [comment]
I see no changes still, if you think you have fixed, feel free to message/talk to me to clarify issue.

**Comment by jefflien8** [comment]
已改正 麻煩老師檢查

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
